/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Store;

import direct.market.datatype.DataCategoria;
import direct.market.datatype.DataProducto;
import direct.market.exceptions.CategoryException;
import direct.market.exceptions.ProductoException;
import direct.market.factory.Factory;
import java.awt.Image;
import java.beans.PropertyVetoException;
import java.util.ArrayList;
import java.util.Enumeration;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author kavesa
 */
public class InfoProducto extends javax.swing.JInternalFrame {

    /**
     * Creates new form InfoProducto
     */
    public InfoProducto() {
        initComponents();
        cargarCategorias();
    }

    public static InfoProducto getInstancia() {
        if (IProdInstancia == null) {
            IProdInstancia = new InfoProducto();
        }
        return IProdInstancia;
    }

    public DefaultMutableTreeNode searchNode(String nodeStr) {
        DefaultTreeModel modelito = (DefaultTreeModel) treeCategoria.getModel();
        DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) modelito.getRoot();

        DefaultMutableTreeNode node = null;
        Enumeration e = raiz.breadthFirstEnumeration();
        while (e.hasMoreElements()) {
            node = (DefaultMutableTreeNode) e.nextElement();
            if (nodeStr.equals(node.getUserObject().toString())) {
                return node;
            }
        }
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCategoria = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        treeCategoria = new javax.swing.JTree();
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        listProductos = new javax.swing.JList();
        jPanel2 = new javax.swing.JPanel();
        btCategoria = new javax.swing.JButton();
        btProducto = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        pnlInformacion = new javax.swing.JTabbedPane();
        pnlDatos = new javax.swing.JPanel();
        tfNombre = new javax.swing.JTextField();
        tfReferencia = new javax.swing.JTextField();
        tfProveedor = new javax.swing.JTextField();
        txtNombre = new javax.swing.JLabel();
        txtNumeroReferencia = new javax.swing.JLabel();
        txtProveedor = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JLabel();
        txtEspecificacion = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        taDescripcion = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        taEspecificacion = new javax.swing.JTextArea();
        pnlImagenes = new javax.swing.JPanel();
        panelImagen = new javax.swing.JPanel();
        lblImagenActual = new javax.swing.JLabel();
        cbImagenes = new javax.swing.JComboBox();
        pnlCategorias = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listCategorias = new javax.swing.JList();
        lblMensaje = new javax.swing.JLabel();

        setMaximizable(true);
        setResizable(true);
        setTitle("Ver Informacion de Producto");
        getContentPane().setLayout(null);

        panelCategoria.setBackground(new java.awt.Color(214, 228, 237));
        panelCategoria.setBorder(javax.swing.BorderFactory.createMatteBorder(8, 8, 8, 8, new javax.swing.ImageIcon(getClass().getResource("/Store/Recursos/backgroundP2.jpg")))); // NOI18N

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Categorias");
        treeCategoria.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane1.setViewportView(treeCategoria);

        jPanel1.setBackground(new java.awt.Color(214, 228, 237));
        jPanel1.setLayout(new java.awt.GridLayout(1, 2, 8, 0));

        jTextField1.setEditable(false);
        jTextField1.setText("Seleccione una Categoria");
        jPanel1.add(jTextField1);

        jTextField2.setEditable(false);
        jTextField2.setText("Seleccione el Producto");
        jPanel1.add(jTextField2);

        jScrollPane2.setViewportView(listProductos);

        javax.swing.GroupLayout panelCategoriaLayout = new javax.swing.GroupLayout(panelCategoria);
        panelCategoria.setLayout(panelCategoriaLayout);
        panelCategoriaLayout.setHorizontalGroup(
            panelCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(panelCategoriaLayout.createSequentialGroup()
                .addGroup(panelCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCategoriaLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelCategoriaLayout.setVerticalGroup(
            panelCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCategoriaLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        getContentPane().add(panelCategoria);
        panelCategoria.setBounds(10, 20, 420, 470);

        jPanel2.setBackground(new java.awt.Color(214, 228, 237));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(8, 8, 8, 8, new javax.swing.ImageIcon(getClass().getResource("/Store/Recursos/backgroundP2.jpg")))); // NOI18N
        jPanel2.setLayout(new java.awt.GridLayout(1, 2, 8, 0));

        btCategoria.setText("Seleccionar");
        btCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCategoriaActionPerformed(evt);
            }
        });
        jPanel2.add(btCategoria);

        btProducto.setText("Seleccionar");
        btProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProductoActionPerformed(evt);
            }
        });
        jPanel2.add(btProducto);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 500, 420, 50);

        jPanel3.setBackground(new java.awt.Color(214, 228, 237));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(8, 8, 8, 8, new javax.swing.ImageIcon(getClass().getResource("/Store/Recursos/backgroundP2.jpg")))); // NOI18N
        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        jButton1.setText("Cerrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(610, 500, 170, 50);

        jPanel4.setBackground(new java.awt.Color(214, 228, 237));
        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(8, 8, 8, 8, new javax.swing.ImageIcon(getClass().getResource("/Store/Recursos/backgroundP2.jpg")))); // NOI18N
        jPanel4.setLayout(null);

        pnlInformacion.setBorder(null);
        pnlInformacion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pnlInformacionFocusGained(evt);
            }
        });

        tfNombre.setEditable(false);

        tfReferencia.setEditable(false);

        tfProveedor.setEditable(false);

        txtNombre.setText("Nombre");

        txtNumeroReferencia.setText("Referencia");

        txtProveedor.setText("Proveedor");

        txtDescripcion.setText("Descripcion");

        txtEspecificacion.setText("Especificacion");

        jScrollPane4.setAutoscrolls(true);
        jScrollPane4.setPreferredSize(new java.awt.Dimension(262, 40));

        taDescripcion.setEditable(false);
        taDescripcion.setColumns(20);
        taDescripcion.setLineWrap(true);
        taDescripcion.setRows(5);
        taDescripcion.setPreferredSize(new java.awt.Dimension(260, 40));
        jScrollPane4.setViewportView(taDescripcion);

        taEspecificacion.setEditable(false);
        taEspecificacion.setColumns(20);
        taEspecificacion.setLineWrap(true);
        taEspecificacion.setRows(5);
        jScrollPane5.setViewportView(taEspecificacion);

        javax.swing.GroupLayout pnlDatosLayout = new javax.swing.GroupLayout(pnlDatos);
        pnlDatos.setLayout(pnlDatosLayout);
        pnlDatosLayout.setHorizontalGroup(
            pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDatosLayout.createSequentialGroup()
                        .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDescripcion)
                            .addComponent(txtProveedor)
                            .addComponent(txtNumeroReferencia)
                            .addComponent(txtNombre))
                        .addGap(29, 29, 29)
                        .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfReferencia)
                            .addComponent(tfNombre)
                            .addComponent(tfProveedor, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(pnlDatosLayout.createSequentialGroup()
                        .addComponent(txtEspecificacion)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlDatosLayout.setVerticalGroup(
            pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre)
                    .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumeroReferencia)
                    .addComponent(tfReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProveedor)
                    .addComponent(tfProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(txtDescripcion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEspecificacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE))
        );

        pnlInformacion.addTab("Datos Generales", pnlDatos);

        panelImagen.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout panelImagenLayout = new javax.swing.GroupLayout(panelImagen);
        panelImagen.setLayout(panelImagenLayout);
        panelImagenLayout.setHorizontalGroup(
            panelImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblImagenActual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelImagenLayout.setVerticalGroup(
            panelImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblImagenActual, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
        );

        cbImagenes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbImagenesItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout pnlImagenesLayout = new javax.swing.GroupLayout(pnlImagenes);
        pnlImagenes.setLayout(pnlImagenesLayout);
        pnlImagenesLayout.setHorizontalGroup(
            pnlImagenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlImagenesLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlImagenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbImagenes, 0, 282, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        pnlImagenesLayout.setVerticalGroup(
            pnlImagenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlImagenesLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(cbImagenes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlInformacion.addTab("Imagenes", pnlImagenes);

        jScrollPane3.setViewportView(listCategorias);

        javax.swing.GroupLayout pnlCategoriasLayout = new javax.swing.GroupLayout(pnlCategorias);
        pnlCategorias.setLayout(pnlCategoriasLayout);
        pnlCategoriasLayout.setHorizontalGroup(
            pnlCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCategoriasLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        pnlCategoriasLayout.setVerticalGroup(
            pnlCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCategoriasLayout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        pnlInformacion.addTab("Categorias", pnlCategorias);

        jPanel4.add(pnlInformacion);
        pnlInformacion.setBounds(10, 10, 330, 450);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(430, 20, 350, 470);

        lblMensaje.setForeground(new java.awt.Color(255, 0, 0));
        lblMensaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Store/Recursos/background.jpg"))); // NOI18N
        getContentPane().add(lblMensaje);
        lblMensaje.setBounds(0, -1, 800, 570);

        setBounds(0, 0, 800, 600);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        IProdInstancia = null;
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProductoActionPerformed
        if (!listProductos.isSelectionEmpty()) {
            DataProducto dprod = null;
            try {
                dprod = Factory.getInstance().getProductoController().buscarProductoPorName(listProductos.getSelectedValue().toString());


                tfNombre.setText(dprod.getNombre());
                tfReferencia.setText(dprod.getReferencia());
                tfProveedor.setText(dprod.getDataProveedor().getCompania());
                taDescripcion.setText(dprod.getDataEspecificacion().getDescripcion());
                taEspecificacion.setText(dprod.getDataEspecificacion().getEspecificacion());

                //lista categorias
                DefaultListModel dlm = new DefaultListModel();

                List<DataCategoria> catList = new ArrayList<DataCategoria>();
                catList = Factory.getInstance().getCategoriaController().getCategoriasDeProducto(dprod.getReferencia());

                for (DataCategoria dc : catList) {
                    dlm.addElement(dc.getNombre());
                }

                if (!dprod.getDataEspecificacion().getImagenes().isEmpty()) {
                    cbImagenes.removeAllItems();
                    List<String> imagenes = new ArrayList<String>();
                    imagenes = dprod.getDataEspecificacion().getImagenes();
                    for (String imagen : imagenes) {
                        cbImagenes.addItem(imagen);
                    }
                    //cbImagenes.setSelectedIndex(0);
                } else {
                    cbImagenes.removeAllItems();
                }
                reloadTabImagenes();

                listCategorias.setModel(dlm);
            } catch (CategoryException ex) {
                Logger.getLogger(InfoProducto.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ProductoException ex) {
                Logger.getLogger(InfoProducto.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            lblMensaje.setText("Debe seleccionar un producto");
        }
    }//GEN-LAST:event_btProductoActionPerformed

    private void btCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCategoriaActionPerformed
        lblMensaje.setText("");
        DefaultTreeModel modelo = (DefaultTreeModel) treeCategoria.getModel();
        DefaultMutableTreeNode seleccionado = (DefaultMutableTreeNode) treeCategoria.getLastSelectedPathComponent();
        DefaultListModel dlm = new DefaultListModel();
        if (seleccionado != null) {
            if (seleccionado.isLeaf()) {//arreglar
                List<DataProducto> productos = new ArrayList<DataProducto>();
                try {
                    productos = Factory.getInstance().getCategoriaController().getProductosPorNombreCategoria(seleccionado.getUserObject().toString());
                } catch (CategoryException ex) {
                    Logger.getLogger(InfoProducto.class.getName()).log(Level.SEVERE, null, ex);
                }
                for (DataProducto dp : productos) {
                    dlm.addElement(dp.getNombre());
                }
                listProductos.setModel(dlm);
            } else {
                lblMensaje.setText("Debe seleccionar una categoria sin subcategorias");
            }
        } else {
            lblMensaje.setText("Debe seleccionar una categoria");
        }
    }//GEN-LAST:event_btCategoriaActionPerformed

    private void pnlInformacionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pnlInformacionFocusGained
        reloadTabImagenes();

    }//GEN-LAST:event_pnlInformacionFocusGained

    private void cbImagenesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbImagenesItemStateChanged
        reloadTabImagenes();

    }//GEN-LAST:event_cbImagenesItemStateChanged

    private void reloadTabImagenes(){
        if (cbImagenes.getItemCount() > 0) {
            ImageIcon imageIcon = new ImageIcon(cbImagenes.getSelectedItem().toString());
            lblImagenActual.setIcon(new ImageIcon(imageIcon.getImage().getScaledInstance(lblImagenActual.getWidth(), -1, Image.SCALE_AREA_AVERAGING)));
            lblImagenActual.repaint();
        }else{
            lblImagenActual.setIcon(null);
            lblImagenActual.revalidate();
        }

    }
    
    private void cargarCategorias() {
        try {
            List<DataCategoria> categorias = Factory.getInstance().getCategoriaController().getCategorias();

            DefaultTreeModel modelo = (DefaultTreeModel) treeCategoria.getModel();
            DefaultMutableTreeNode root = (DefaultMutableTreeNode) modelo.getRoot();
            DefaultMutableTreeNode nuevo;
            DefaultMutableTreeNode padre;

            for (DataCategoria dc : categorias) {
                if (dc.getParent().equals("Categorias")) {
                    nuevo = new DefaultMutableTreeNode(dc.getNombre());
                    root.add(nuevo);
                } else {
                    nuevo = new DefaultMutableTreeNode(dc.getNombre());
                    padre = searchNode(dc.getParent());
                    modelo.insertNodeInto(nuevo, padre, padre.getChildCount());


                }
            }
        } catch (Exception ex) {
            Logger.getLogger(InfoProducto.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCategoria;
    private javax.swing.JButton btProducto;
    private javax.swing.JComboBox cbImagenes;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lblImagenActual;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JList listCategorias;
    private javax.swing.JList listProductos;
    private javax.swing.JPanel panelCategoria;
    private javax.swing.JPanel panelImagen;
    private javax.swing.JPanel pnlCategorias;
    private javax.swing.JPanel pnlDatos;
    private javax.swing.JPanel pnlImagenes;
    private javax.swing.JTabbedPane pnlInformacion;
    private javax.swing.JTextArea taDescripcion;
    private javax.swing.JTextArea taEspecificacion;
    private javax.swing.JTextField tfNombre;
    private javax.swing.JTextField tfProveedor;
    private javax.swing.JTextField tfReferencia;
    private javax.swing.JTree treeCategoria;
    private javax.swing.JLabel txtDescripcion;
    private javax.swing.JLabel txtEspecificacion;
    private javax.swing.JLabel txtNombre;
    private javax.swing.JLabel txtNumeroReferencia;
    private javax.swing.JLabel txtProveedor;
    // End of variables declaration//GEN-END:variables
    private static InfoProducto IProdInstancia;
}
