/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Store;

import direct.market.datatype.DataCategoria;
import direct.market.datatype.DataProducto;
import direct.market.exceptions.CategoryException;
import direct.market.exceptions.ProductoException;
import direct.market.factory.Factory;
import java.awt.Image;
import java.beans.PropertyVetoException;
import java.io.File;
import java.util.ArrayList;
import java.util.Enumeration;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreeNode;

/**
 *
 * @author kavesa
 */
public class InfoProducto extends javax.swing.JInternalFrame {

    /**
     * Creates new form InfoProducto
     */
    public InfoProducto() {
        initComponents();
        cargarCategorias();
    }

    public static InfoProducto getInstancia() {
        if (IProdInstancia == null) {
            IProdInstancia = new InfoProducto();
        }
        return IProdInstancia;
    }

    public DefaultMutableTreeNode searchNode(String nodeStr) {
        DefaultTreeModel modelito = (DefaultTreeModel) treeCategoria.getModel();
        DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) modelito.getRoot();

        DefaultMutableTreeNode node = null;
        Enumeration e = raiz.breadthFirstEnumeration();
        while (e.hasMoreElements()) {
            node = (DefaultMutableTreeNode) e.nextElement();
            if (nodeStr.equals(node.getUserObject().toString())) {
                return node;
            }
        }
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCategoria = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        treeCategoria = new javax.swing.JTree();
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        listProductos = new javax.swing.JList();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        pnlInformacion = new javax.swing.JTabbedPane();
        pnlDatos = new javax.swing.JPanel();
        tfNombre = new javax.swing.JTextField();
        tfReferencia = new javax.swing.JTextField();
        tfProveedor = new javax.swing.JTextField();
        txtNombre = new javax.swing.JLabel();
        txtNumeroReferencia = new javax.swing.JLabel();
        txtProveedor = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JLabel();
        txtEspecificacion = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        taDescripcion = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        taEspecificacion = new javax.swing.JTextArea();
        txtPrecio = new javax.swing.JLabel();
        tfPrecio = new javax.swing.JTextField();
        pnlImagenes = new javax.swing.JPanel();
        panelImagen = new javax.swing.JPanel();
        lblImagenActual = new javax.swing.JLabel();
        cbImagenes = new javax.swing.JComboBox();
        pnlCategorias = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listCategorias = new javax.swing.JList();
        lblRutaCategoria = new javax.swing.JLabel();
        lblMensaje = new javax.swing.JLabel();

        setMaximizable(true);
        setResizable(true);
        setTitle("Ver Informacion de Producto");
        getContentPane().setLayout(null);

        panelCategoria.setBackground(new java.awt.Color(214, 228, 237));
        panelCategoria.setBorder(javax.swing.BorderFactory.createMatteBorder(8, 8, 8, 8, new javax.swing.ImageIcon(getClass().getResource("/Store/Recursos/backgroundP2.jpg")))); // NOI18N

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Categorias");
        treeCategoria.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        treeCategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                treeCategoriaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(treeCategoria);

        jPanel1.setBackground(new java.awt.Color(214, 228, 237));
        jPanel1.setLayout(new java.awt.GridLayout(1, 2, 8, 0));

        jTextField1.setEditable(false);
        jTextField1.setText("Seleccione una Categoria");
        jPanel1.add(jTextField1);

        jTextField2.setEditable(false);
        jTextField2.setText("Seleccione el Producto");
        jPanel1.add(jTextField2);

        listProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listProductosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(listProductos);

        javax.swing.GroupLayout panelCategoriaLayout = new javax.swing.GroupLayout(panelCategoria);
        panelCategoria.setLayout(panelCategoriaLayout);
        panelCategoriaLayout.setHorizontalGroup(
            panelCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(panelCategoriaLayout.createSequentialGroup()
                .addGroup(panelCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCategoriaLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelCategoriaLayout.setVerticalGroup(
            panelCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCategoriaLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        getContentPane().add(panelCategoria);
        panelCategoria.setBounds(10, 20, 420, 470);

        jPanel3.setBackground(new java.awt.Color(214, 228, 237));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(8, 8, 8, 8, new javax.swing.ImageIcon(getClass().getResource("/Store/Recursos/backgroundP2.jpg")))); // NOI18N
        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        jButton1.setText("Cerrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(610, 500, 170, 50);

        jPanel4.setBackground(new java.awt.Color(214, 228, 237));
        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(8, 8, 8, 8, new javax.swing.ImageIcon(getClass().getResource("/Store/Recursos/backgroundP2.jpg")))); // NOI18N
        jPanel4.setLayout(new java.awt.GridLayout(1, 0));

        pnlInformacion.setBorder(null);
        pnlInformacion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pnlInformacionFocusGained(evt);
            }
        });

        tfNombre.setEditable(false);

        tfReferencia.setEditable(false);

        tfProveedor.setEditable(false);

        txtNombre.setText("Nombre");

        txtNumeroReferencia.setText("Referencia");

        txtProveedor.setText("Proveedor");

        txtDescripcion.setText("Descripcion");

        txtEspecificacion.setText("Especificacion");

        jScrollPane4.setAutoscrolls(true);
        jScrollPane4.setPreferredSize(new java.awt.Dimension(262, 40));

        taDescripcion.setEditable(false);
        taDescripcion.setColumns(20);
        taDescripcion.setLineWrap(true);
        taDescripcion.setRows(5);
        taDescripcion.setPreferredSize(new java.awt.Dimension(260, 40));
        jScrollPane4.setViewportView(taDescripcion);

        taEspecificacion.setEditable(false);
        taEspecificacion.setColumns(20);
        taEspecificacion.setLineWrap(true);
        taEspecificacion.setRows(5);
        jScrollPane5.setViewportView(taEspecificacion);

        txtPrecio.setText("Precio");

        tfPrecio.setEditable(false);

        javax.swing.GroupLayout pnlDatosLayout = new javax.swing.GroupLayout(pnlDatos);
        pnlDatos.setLayout(pnlDatosLayout);
        pnlDatosLayout.setHorizontalGroup(
            pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDatosLayout.createSequentialGroup()
                        .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtProveedor)
                            .addComponent(txtNumeroReferencia)
                            .addComponent(txtNombre))
                        .addGap(36, 36, 36)
                        .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfReferencia)
                            .addComponent(tfNombre)
                            .addComponent(tfProveedor, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDatosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtDescripcion)
                        .addGap(220, 220, 220))
                    .addGroup(pnlDatosLayout.createSequentialGroup()
                        .addComponent(txtEspecificacion)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlDatosLayout.createSequentialGroup()
                        .addComponent(txtPrecio)
                        .addGap(64, 64, 64)
                        .addComponent(tfPrecio)))
                .addContainerGap())
        );
        pnlDatosLayout.setVerticalGroup(
            pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre)
                    .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumeroReferencia)
                    .addComponent(tfReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrecio)
                    .addComponent(tfPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProveedor)
                    .addComponent(tfProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(txtDescripcion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtEspecificacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE))
        );

        pnlInformacion.addTab("Datos Generales", pnlDatos);

        panelImagen.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout panelImagenLayout = new javax.swing.GroupLayout(panelImagen);
        panelImagen.setLayout(panelImagenLayout);
        panelImagenLayout.setHorizontalGroup(
            panelImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblImagenActual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelImagenLayout.setVerticalGroup(
            panelImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblImagenActual, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
        );

        cbImagenes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbImagenesItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout pnlImagenesLayout = new javax.swing.GroupLayout(pnlImagenes);
        pnlImagenes.setLayout(pnlImagenesLayout);
        pnlImagenesLayout.setHorizontalGroup(
            pnlImagenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlImagenesLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlImagenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbImagenes, 0, 282, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        pnlImagenesLayout.setVerticalGroup(
            pnlImagenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlImagenesLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(cbImagenes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlInformacion.addTab("Imagenes", pnlImagenes);

        listCategorias.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listCategoriasValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(listCategorias);

        javax.swing.GroupLayout pnlCategoriasLayout = new javax.swing.GroupLayout(pnlCategorias);
        pnlCategorias.setLayout(pnlCategoriasLayout);
        pnlCategoriasLayout.setHorizontalGroup(
            pnlCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCategoriasLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCategoriasLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(lblRutaCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        pnlCategoriasLayout.setVerticalGroup(
            pnlCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCategoriasLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblRutaCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        pnlInformacion.addTab("Categorias", pnlCategorias);

        jPanel4.add(pnlInformacion);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(440, 20, 340, 470);

        lblMensaje.setForeground(new java.awt.Color(255, 0, 0));
        lblMensaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Store/Recursos/background.jpg"))); // NOI18N
        getContentPane().add(lblMensaje);
        lblMensaje.setBounds(0, -1, 800, 570);

        setBounds(0, 0, 800, 600);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        IProdInstancia = null;
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void pnlInformacionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pnlInformacionFocusGained
        reloadTabImagenes();

    }//GEN-LAST:event_pnlInformacionFocusGained

    private void cbImagenesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbImagenesItemStateChanged
        reloadTabImagenes();

    }//GEN-LAST:event_cbImagenesItemStateChanged

    private void listCategoriasValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listCategoriasValueChanged
        if (listCategorias.getModel().getSize() > 0 && !listCategorias.isSelectionEmpty()) {
            TreeNode[] rutaNodos = searchNode(listCategorias.getSelectedValue().toString()).getPath();
            String rutaCat = "";
            for (int i = 0; i < rutaNodos.length; i++) {
                rutaCat += rutaNodos[i];
                if (i + 1 < rutaNodos.length) {
                    rutaCat += " " + File.separator;
                }
            }
            lblRutaCategoria.setText("<html><body style='width:200px'>"+rutaCat+"</html>");
        }
    }//GEN-LAST:event_listCategoriasValueChanged

    private void treeCategoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_treeCategoriaMouseClicked
        
        lblMensaje.setText("");
        DefaultTreeModel modelo = (DefaultTreeModel) treeCategoria.getModel();
        DefaultMutableTreeNode seleccionado = (DefaultMutableTreeNode) treeCategoria.getLastSelectedPathComponent();
        DefaultListModel dlm = new DefaultListModel();
        if (seleccionado != null) {
            if (seleccionado.isLeaf()) {//arreglar
                List<DataProducto> productos = new ArrayList<DataProducto>();
                try {
                    productos = Factory.getInstance().getCategoriaController().getProductosPorNombreCategoria(seleccionado.getUserObject().toString());
                } catch (CategoryException ex) {
                    Logger.getLogger(InfoProducto.class.getName()).log(Level.SEVERE, null, ex);
                }
                for (DataProducto dp : productos) {
                    dlm.addElement(dp.getNombre());
                }
                listProductos.setModel(dlm);
            } else {
                lblMensaje.setText("Debe seleccionar una categoria sin subcategorias");
            }
        } else {
            lblMensaje.setText("Debe seleccionar una categoria");
        }
        
    }//GEN-LAST:event_treeCategoriaMouseClicked

    String prodN=null;
    
    private void listProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listProductosMouseClicked
        
        if (!listProductos.isSelectionEmpty()) {
            lblRutaCategoria.setText("");
            DataProducto dprod = null;
            try {
                prodN = listProductos.getSelectedValue().toString();
                dprod = Factory.getInstance().getProductoController().buscarProductoPorName(prodN);


                tfNombre.setText(dprod.getNombre());
                tfReferencia.setText(dprod.getReferencia());
                tfPrecio.setText(String.valueOf(dprod.getDataEspecificacion().getPrecio()));
                tfProveedor.setText(dprod.getDataProveedor().getCompania());
                taDescripcion.setText(dprod.getDataEspecificacion().getDescripcion());
                taEspecificacion.setText(dprod.getDataEspecificacion().getEspecificacion());

                //lista categorias
                DefaultListModel dlm = new DefaultListModel();

                List<DataCategoria> catList = new ArrayList<DataCategoria>();
                catList = Factory.getInstance().getCategoriaController().getCategoriasDeProducto(dprod.getReferencia());

                for (DataCategoria dc : catList) {
                    dlm.addElement(dc.getNombre());
                }
                listCategorias.validate();

                if (!dprod.getDataEspecificacion().getImagenes().isEmpty()) {
                    cbImagenes.removeAllItems();
                    int tama = dprod.getDataEspecificacion().getImagenes().size();
                    //List<byte[]> imagenes = dprod.getDataEspecificacion().getImagenes();
                    for (Integer i = 1; i <= tama; i++) {
                        cbImagenes.addItem("Imagen 0"+i.toString());
                    }
                    //cbImagenes.setSelectedIndex(0);
                } else {
                    cbImagenes.removeAllItems();
                }
                reloadTabImagenes();

                listCategorias.setModel(dlm);
            } catch (CategoryException ex) {
                Logger.getLogger(InfoProducto.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ProductoException ex) {
                Logger.getLogger(InfoProducto.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            lblMensaje.setText("Debe seleccionar un producto");
        }
        
    }//GEN-LAST:event_listProductosMouseClicked

    private void reloadTabImagenes() {
        if (cbImagenes.getItemCount() > 0) {
            try {
                int cont = cbImagenes.getSelectedIndex();
                DataProducto dprod = Factory.getInstance().getProductoController().buscarProductoPorName(prodN);
                List<byte[]> imagenes = dprod.getDataEspecificacion().getImagenes();
                ImageIcon imageIcon = new ImageIcon(imagenes.get(cont));
                    lblImagenActual.setIcon(new ImageIcon(imageIcon.getImage().getScaledInstance(lblImagenActual.getWidth(), -1, Image.SCALE_AREA_AVERAGING)));
                    lblImagenActual.repaint();
                
    //            ImageIcon imageIcon = new ImageIcon(getClass().getResource(cbImagenes.getSelectedItem().toString()));
    //            lblImagenActual.repaint();
    //            lblImagenActual.repaint();
            } catch (ProductoException ex) {
                Logger.getLogger(InfoProducto.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            lblImagenActual.setIcon(null);
            lblImagenActual.revalidate();
        }

    }

    private void cargarCategorias() {
        try {
            List<DataCategoria> categorias = Factory.getInstance().getCategoriaController().getCategorias();

            DefaultTreeModel modelo = (DefaultTreeModel) treeCategoria.getModel();
            DefaultMutableTreeNode root = (DefaultMutableTreeNode) modelo.getRoot();
            DefaultMutableTreeNode nuevo;
            DefaultMutableTreeNode padre;

            for (DataCategoria dc : categorias) {
                if (dc.getParent().equals("Categorias")) {
                    nuevo = new DefaultMutableTreeNode(dc.getNombre());
                    root.add(nuevo);
                } else {
                    nuevo = new DefaultMutableTreeNode(dc.getNombre());
                    padre = searchNode(dc.getParent());
                    modelo.insertNodeInto(nuevo, padre, padre.getChildCount());


                }
            }
        } catch (Exception ex) {
            Logger.getLogger(InfoProducto.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbImagenes;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lblImagenActual;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JLabel lblRutaCategoria;
    private javax.swing.JList listCategorias;
    private javax.swing.JList listProductos;
    private javax.swing.JPanel panelCategoria;
    private javax.swing.JPanel panelImagen;
    private javax.swing.JPanel pnlCategorias;
    private javax.swing.JPanel pnlDatos;
    private javax.swing.JPanel pnlImagenes;
    private javax.swing.JTabbedPane pnlInformacion;
    private javax.swing.JTextArea taDescripcion;
    private javax.swing.JTextArea taEspecificacion;
    private javax.swing.JTextField tfNombre;
    private javax.swing.JTextField tfPrecio;
    private javax.swing.JTextField tfProveedor;
    private javax.swing.JTextField tfReferencia;
    private javax.swing.JTree treeCategoria;
    private javax.swing.JLabel txtDescripcion;
    private javax.swing.JLabel txtEspecificacion;
    private javax.swing.JLabel txtNombre;
    private javax.swing.JLabel txtNumeroReferencia;
    private javax.swing.JLabel txtPrecio;
    private javax.swing.JLabel txtProveedor;
    // End of variables declaration//GEN-END:variables
    private static InfoProducto IProdInstancia;
}
