/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Store;

import java.awt.Image;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lufasoch
 */
public class InfoCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form InfoCliente
     */
    public InfoCliente() {
        initComponents();
        this.validate();
        Actualizar();
        
        
    }

    public ImageIcon RZIma(String DirRelativa, int Ancho, int Alto)
    {
        ImageIcon IcoIco = new ImageIcon(getClass().getResource(DirRelativa));
        Image img = IcoIco.getImage();  
        Image newimg = img.getScaledInstance(Ancho, Alto,  java.awt.Image.SCALE_SMOOTH);          
        IcoIco = new ImageIcon(newimg); 
        return IcoIco;
    }
    
    public static InfoCliente getInstancia() {
        if (ICInstancia == null) {
            ICInstancia = new InfoCliente();
        }
        return ICInstancia;
    }
    
    public void Actualizar()
    {
        //// Agregar imagen y cambiar tamaño de la foto del perfil ////        
        String DirI = "Recursos/Perfil.jpg";
        PerfilLabel.setIcon(RZIma(DirI,150,150));
        //// Se buscan los clientes
        //ABAJO//DATOS DEVUELTOS
        String[] Nicknames = { "Lufasoch", "Andres", "Clobes", "Mariza", "JuanPablo" };
        String[] eMails = { "lufasoch@gmail.com", "kerveza@gmail.com", "clobesney1@gmail.com", "maryleon1982@gmail.com", "jpmc21891@gmail.com" };
        //ABAJO//CAMBIAR MODELO DE LA TABLA
        DefaultTableModel DTM2 = new DefaultTableModel(0, 0);
        String header[] = new String[] { "Nickname", "eMail" };
        DTM2.setColumnIdentifiers(header);
        ClientesTable.setModel(DTM2);
        ClientesTable.getColumnModel().getColumn(0).setPreferredWidth(23);
        //ARRIBA//CAMBIAR MODELO DE LA TABLA
        
        int cont = 0;//MIENTRAS NO TENGO UNA LISTA DE CLIENTES USO UN CONTADOR        
        while(cont < 5)
        {
            DTM2.addRow(new Object[] { Nicknames[cont], eMails[cont] }); 
            cont++;
        }
        //ClientesTable.setValueAt("Lufasoch", 0, 0);
        //ClientesTable.setValueAt("lufasoch@gmail.com", 0, 1);
    }
    
    public void limpiarCampos()
    {
        TTipoUC.setText("");
        TNicknameC.setText("");
        TNombreC.setText("");
        TApellidoC.setText("");
        TeMailC.setText("");
        TFechaNacC.setText("");
        PerfilLabel.setIcon(RZIma("Recursos/Perfil.jpg",150,150));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ClientesTable = new javax.swing.JTable();
        PPanel = new javax.swing.JPanel();
        PerfilLabel = new javax.swing.JLabel();
        InfoPanel = new javax.swing.JPanel();
        TNickname = new javax.swing.JTextField();
        TNicknameC = new javax.swing.JTextField();
        TeMail = new javax.swing.JTextField();
        TeMailC = new javax.swing.JTextField();
        TNombre = new javax.swing.JTextField();
        TNombreC = new javax.swing.JTextField();
        TApellido = new javax.swing.JTextField();
        TApellidoC = new javax.swing.JTextField();
        TFechaNac = new javax.swing.JTextField();
        TFechaNacC = new javax.swing.JTextField();
        TTipoU = new javax.swing.JTextField();
        TTipoUC = new javax.swing.JTextField();
        OrdenesPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        OrdenesTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        ActualizarButton = new javax.swing.JButton();
        VerInfoButton = new javax.swing.JButton();
        OrdenButton = new javax.swing.JButton();
        Cerrar = new javax.swing.JButton();
        BackgroundLabel = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(800, 600));
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        getContentPane().setLayout(null);

        TPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(8, 8, 8, 8, new javax.swing.ImageIcon(getClass().getResource("/Store/Recursos/backgroundP2.jpg")))); // NOI18N

        ClientesTable.setAutoCreateRowSorter(true);
        ClientesTable.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        ClientesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "Nickname", "eMail"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ClientesTable.setFillsViewportHeight(true);
        ClientesTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(ClientesTable);

        javax.swing.GroupLayout TPanelLayout = new javax.swing.GroupLayout(TPanel);
        TPanel.setLayout(TPanelLayout);
        TPanelLayout.setHorizontalGroup(
            TPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
        );
        TPanelLayout.setVerticalGroup(
            TPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
        );

        getContentPane().add(TPanel);
        TPanel.setBounds(40, 50, 310, 410);

        PPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(8, 8, 8, 8, new javax.swing.ImageIcon(getClass().getResource("/Store/Recursos/backgroundP2.jpg")))); // NOI18N
        PPanel.setLayout(null);

        PerfilLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Store/Recursos/Perfil.jpg"))); // NOI18N
        PPanel.add(PerfilLabel);
        PerfilLabel.setBounds(10, 10, 150, 150);

        getContentPane().add(PPanel);
        PPanel.setBounds(580, 50, 170, 170);

        InfoPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(8, 8, 8, 8, new javax.swing.ImageIcon(getClass().getResource("/Store/Recursos/backgroundP2.jpg")))); // NOI18N
        InfoPanel.setLayout(new java.awt.GridLayout(6, 2));

        TNickname.setEditable(false);
        TNickname.setBackground(new java.awt.Color(255, 255, 255));
        TNickname.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        TNickname.setText("Nickname");
        InfoPanel.add(TNickname);

        TNicknameC.setEditable(false);
        TNicknameC.setBackground(new java.awt.Color(255, 255, 255));
        TNicknameC.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        InfoPanel.add(TNicknameC);

        TeMail.setEditable(false);
        TeMail.setBackground(new java.awt.Color(255, 255, 255));
        TeMail.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        TeMail.setText("eMail");
        InfoPanel.add(TeMail);

        TeMailC.setEditable(false);
        TeMailC.setBackground(new java.awt.Color(255, 255, 255));
        TeMailC.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        InfoPanel.add(TeMailC);

        TNombre.setEditable(false);
        TNombre.setBackground(new java.awt.Color(255, 255, 255));
        TNombre.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        TNombre.setText("Nombre");
        InfoPanel.add(TNombre);

        TNombreC.setEditable(false);
        TNombreC.setBackground(new java.awt.Color(255, 255, 255));
        TNombreC.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        InfoPanel.add(TNombreC);

        TApellido.setEditable(false);
        TApellido.setBackground(new java.awt.Color(255, 255, 255));
        TApellido.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        TApellido.setText("Apellido");
        InfoPanel.add(TApellido);

        TApellidoC.setEditable(false);
        TApellidoC.setBackground(new java.awt.Color(255, 255, 255));
        TApellidoC.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        InfoPanel.add(TApellidoC);

        TFechaNac.setEditable(false);
        TFechaNac.setBackground(new java.awt.Color(255, 255, 255));
        TFechaNac.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        TFechaNac.setText("Fecha de Nacimiento");
        InfoPanel.add(TFechaNac);

        TFechaNacC.setEditable(false);
        TFechaNacC.setBackground(new java.awt.Color(255, 255, 255));
        TFechaNacC.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        InfoPanel.add(TFechaNacC);

        TTipoU.setEditable(false);
        TTipoU.setBackground(new java.awt.Color(255, 255, 255));
        TTipoU.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        TTipoU.setText("Tipo de Usuario");
        InfoPanel.add(TTipoU);

        TTipoUC.setEditable(false);
        TTipoUC.setBackground(new java.awt.Color(255, 255, 255));
        TTipoUC.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        InfoPanel.add(TTipoUC);

        getContentPane().add(InfoPanel);
        InfoPanel.setBounds(390, 240, 360, 220);

        OrdenesPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(8, 8, 8, 8, new javax.swing.ImageIcon(getClass().getResource("/Store/Recursos/backgroundP2.jpg")))); // NOI18N

        OrdenesTable.setAutoCreateRowSorter(true);
        OrdenesTable.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        OrdenesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        OrdenesTable.setFillsViewportHeight(true);
        OrdenesTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(OrdenesTable);

        javax.swing.GroupLayout OrdenesPanelLayout = new javax.swing.GroupLayout(OrdenesPanel);
        OrdenesPanel.setLayout(OrdenesPanelLayout);
        OrdenesPanelLayout.setHorizontalGroup(
            OrdenesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
        );
        OrdenesPanelLayout.setVerticalGroup(
            OrdenesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
        );

        getContentPane().add(OrdenesPanel);
        OrdenesPanel.setBounds(390, 50, 160, 170);

        jPanel1.setBackground(new java.awt.Color(214, 228, 237));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(8, 8, 8, 8, new javax.swing.ImageIcon(getClass().getResource("/Store/Recursos/backgroundP2.jpg")))); // NOI18N
        jPanel1.setLayout(new java.awt.GridLayout(1, 4, 8, 0));

        ActualizarButton.setText("Actualizar");
        ActualizarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarButtonActionPerformed(evt);
            }
        });
        jPanel1.add(ActualizarButton);

        VerInfoButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        VerInfoButton.setText("Ver datos del Cliente");
        VerInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerInfoButtonActionPerformed(evt);
            }
        });
        jPanel1.add(VerInfoButton);

        OrdenButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        OrdenButton.setText("Ver Orden de Compra");
        OrdenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrdenButtonActionPerformed(evt);
            }
        });
        jPanel1.add(OrdenButton);

        Cerrar.setText("Cerrar");
        Cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarActionPerformed(evt);
            }
        });
        jPanel1.add(Cerrar);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(40, 470, 710, 60);

        BackgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Store/Recursos/background.jpg"))); // NOI18N
        getContentPane().add(BackgroundLabel);
        BackgroundLabel.setBounds(0, 0, 790, 570);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VerInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerInfoButtonActionPerformed
        String nicknameP = ClientesTable.getValueAt(ClientesTable.getSelectedRow(), 0).toString();
        //BUSCAR USUARIO A LA BASE DE DATOS
        
        //ABAJO//DATOS DEVUELTOS
        String[] DatosU = {"Lufasoch", "lufasoch@gmail.com", "Fabricio", "Sosa", "Cliente", "Recursos/Usuarios/Lufasoch.png"};
        int[] NOrdenes = {458, 5366, 7552};
        SimpleDateFormat sdf = new SimpleDateFormat("dd MM yyyy");
        java.util.Date FechaU = new Date(88,9,19);     
        //ARRIBA//DATOS DEVUELTOS        
        
        //ABAJO//IMPRIMIR DATOS
        TNicknameC.setText(DatosU[0]);
        TeMailC.setText(DatosU[1]);
        TNombreC.setText(DatosU[2]);
        TApellidoC.setText(DatosU[3]);
        TFechaNacC.setText(sdf.format(FechaU.getTime()));
        TTipoUC.setText(DatosU[4]);
        PerfilLabel.setIcon(RZIma(DatosU[5],150,150));
        
            //ABAJO//CAMBIAR MODELO DE LA TABLA
        DefaultTableModel DTM = new DefaultTableModel(0, 0);
        String header[] = new String[] { "No. Orden" };
        DTM.setColumnIdentifiers(header);
        OrdenesTable.setModel(DTM);
            //ARRIBA//CAMBIAR MODELO DE LA TABLA
        
        int cont = 0;//MIENTRAS NO TENGO UNA LISTA DE CLIENTES USO UN CONTADOR        
        while(cont < 3)
        {
            DTM.addRow(new Object[] { NOrdenes[cont] }); 
            cont++;
        }
        //ARRIBA//IMPRIMIR DATOS
    }//GEN-LAST:event_VerInfoButtonActionPerformed

    private void OrdenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrdenButtonActionPerformed
          ///////////////////////
         //VER ORDEN DE COMPRA//
        ///////////////////////
    }//GEN-LAST:event_OrdenButtonActionPerformed

    private void CerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarActionPerformed
        limpiarCampos();
        this.dispose();
    }//GEN-LAST:event_CerrarActionPerformed

    private void ActualizarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarButtonActionPerformed
        Actualizar();
    }//GEN-LAST:event_ActualizarButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ActualizarButton;
    private javax.swing.JLabel BackgroundLabel;
    private javax.swing.JButton Cerrar;
    private javax.swing.JTable ClientesTable;
    private javax.swing.JPanel InfoPanel;
    private javax.swing.JButton OrdenButton;
    private javax.swing.JPanel OrdenesPanel;
    private javax.swing.JTable OrdenesTable;
    private javax.swing.JPanel PPanel;
    private javax.swing.JLabel PerfilLabel;
    private javax.swing.JTextField TApellido;
    private javax.swing.JTextField TApellidoC;
    private javax.swing.JTextField TFechaNac;
    private javax.swing.JTextField TFechaNacC;
    private javax.swing.JTextField TNickname;
    private javax.swing.JTextField TNicknameC;
    private javax.swing.JTextField TNombre;
    private javax.swing.JTextField TNombreC;
    private javax.swing.JPanel TPanel;
    private javax.swing.JTextField TTipoU;
    private javax.swing.JTextField TTipoUC;
    private javax.swing.JTextField TeMail;
    private javax.swing.JTextField TeMailC;
    private javax.swing.JButton VerInfoButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
    private static InfoCliente ICInstancia;
}
